TIMEOUT = "TIMEOUT"
RATE_LIMITED = "RATE_LIMITED"
CIRCUIT_OPEN = "CIRCUIT_OPEN"
DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
PERMISSION_DENIED = "PERMISSION_DENIED"
APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
VALIDATION_ERROR = "VALIDATION_ERROR"
EXECUTION_ERROR = "EXECUTION_ERROR"

__all__ = [
    "APPROVAL_REQUIRED", "CIRCUIT_OPEN", "DEPENDENCY_UNAVAILABLE", "EXECUTION_ERROR",
    "PERMISSION_DENIED", "RATE_LIMITED", "TIMEOUT", "VALIDATION_ERROR",
]

