-- PGVector 向量知识库表结构
-- 开启向量扩展插件
CREATE EXTENSION IF NOT EXISTS vector;

-- 多语种商品向量知识库，RAG检索专用
CREATE TABLE IF NOT EXISTS vector_goods_kb (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goods_sku VARCHAR(64),
    lang VARCHAR(8), -- en/zh/es/fr
    chunk_text TEXT, -- 分段后的商品文本
    embedding vector(384), -- bge-small输出384维向量
    meta_json JSONB, -- 附加筛选条件：品类、价格区间
    create_time TIMESTAMP DEFAULT NOW()
);

-- HNSW向量相似度索引，百万向量下毫秒级检索
CREATE INDEX IF NOT EXISTS idx_vector_goods_embedding ON vector_goods_kb USING hnsw (embedding vector_cosine_ops);
-- SKU 关联回表，语义检索 hydrate 商品主表用
CREATE INDEX IF NOT EXISTS idx_vector_goods_sku ON vector_goods_kb(goods_sku);

-- Agent 长期向量记忆表
CREATE TABLE IF NOT EXISTS agent_long_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_name VARCHAR(64),
    content TEXT,
    embedding vector(384),
    meta_json JSONB,
    create_time TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_long_memory_agent ON agent_long_memory(agent_name);